#!/bin/bash
# run wiki file

if [ "$#" -ne 1 ]; then 
    echo "Usage: wikit <file.wiki>"
    exit
fi

cd Wikify
java -cp .:xmlbeans.jar:jsoup-1.7.2.jar:poi-3.11.jar:ooxml.jar:schemas.jar:jxl.jar:antlr-4.5-complete.jar $1 
