#!/bin/bash
# translate the wiki file

if [ "$#" -ne 1 ]; then 
    echo "Usage: wikit <file.wiki>"
    exit
fi

set -e
cd Wikify

STR="java"
first="$1"
EMPTY=""
RESULT="${first/wiki/$STR}"
ARG="${first/.wiki/$EMPTY}"
#file.wiki becomes file.java

cat ../$1 | exec java -cp .:$PWD/antlr-4.5-complete.jar Test $ARG
javac $RESULT

if [ -f $PWD/../$ARG ]; then
    rm $PWD/../$ARG
fi
cd ../
ln -s Wikify/$ARG.java $ARG

echo "====== Translation Successful ======"
