#!/bin/bash
# translate the wiki file

if [ "$#" -ne 1 ]; then 
    echo "Usage: wikit <file.wiki>"
    exit
fi

cd Wikify
#CPATH=$PWD/antlr-4.0-complete.jar

STR="java"
first="$1"
EMPTY=""
RESULT="${first/wiki/$STR}"
ARG="${first/.wiki/$EMPTY}"
#file.wiki becomes file.java

cat ../$1 | exec java Test $ARG
javac $RESULT
cd ../
ln -s Wikify/$ARG.java $ARG

echo "====== Translation Successful ======"
